version: '3'
services:
  myapp-main:
    image: finalsprintimage:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://finalspring-sprintapi.cotkikmzpd7m.us-east-1.rds.amazonaws.com/backendapi
      - spring.datasource.password=Pumpkin43
      - spring.datasource.username=admin
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver